### ISSUE TITLE
Allure Reports folder index.html showing NaN when viewed

### ISSUE THREAD

**Issue by vivekchaks** [mmisty/cypress-allure-adapter#43]
i'm running cypress test using maven command in pom.xml. allure-results folder got generated with .json files but when trying to view allure report it is showing NaN error...i have installed new plugin as suggested by cypress people i.e  "@mmisty/cypress-allure-adapter": "^0.10.7"" and made changes as required in other files. Also, i'm using **exec-maven-plugin** in pom.xml to run and generate cypress reports

**NOTE:** Both allure-results and allure-reports folder is under same path i.e src/test/cypress

Can someone help on this.

**Comment by mmisty** [comment]
@vivekchaks hi, 
This is not the problem with the plugin, this is most probably problem with your commands - where you run them and how.

if your `allure-results` are in `configuration/src/test/cypress` folder and you run command `allure generate allure-results --clean -o src/test/cypress/allure-report`  inside `configuration` folder then report will be empty since `allure` cannot find your `configuration/allure-results` folder. 

In order to fix that either change CWD before running the command to generate report or run by `allure generate src/test/cypress/allure-results --clean -o src/test/cypress/allure-report`

**Comment by vivekchaks** [comment]
@mmisty thanks it works fine now as suggested above
